name: CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-examples.txt
    - name: Check formatting (black)
      run: black --line-length 120 --check --diff staticmaps examples tests
    - name: Lint (pylint)
      run: pylint staticmaps examples tests
    - name: Lint (flake8)
      run: flake8 staticmaps examples tests
    - name: Check types (mypy)
      run: mypy staticmaps examples tests
    - name: Run tests (pytest)
      run: python -m pytest tests
